import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import dashboardRouter from "./dashboard";
import marketplaceRouter from "./marketplace";
import dealwiseRouter from "./dealwise";
import qualityscanRouter from "./qualityscan";
import landshareRouter from "./landshare";
import harvestfinanceRouter from "./harvestfinance";
import barterRouter from "./barter";
import agrihaRouter from "./agrihaul";
import communityRouter from "./community";
import impactRouter from "./impact";
import accountingRouter from "./accounting";
import farmscoreRouter from "./farmscore";
import notificationsRouter from "./notifications";
import alertsRouter from "./alerts";
import disputesRouter from "./disputes";
import mentorshipRouter from "./mentorship";
import academyRouter from "./academy";
import farmersRouter from "./farmers";
import uploadRouter from "./upload";
import marketplaceImagesRouter from "./marketplace-images";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(uploadRouter);
router.use(usersRouter);
router.use(dashboardRouter);
router.use(marketplaceRouter);
router.use(farmersRouter);
router.use(dealwiseRouter);
router.use(qualityscanRouter);
router.use(landshareRouter);
router.use(harvestfinanceRouter);
router.use(barterRouter);
router.use(agrihaRouter);
router.use(communityRouter);
router.use(impactRouter);
router.use(accountingRouter);
router.use(farmscoreRouter);
router.use(notificationsRouter);
router.use(alertsRouter);
router.use(disputesRouter);
router.use(mentorshipRouter);
router.use(academyRouter);
router.use(marketplaceImagesRouter);

export default router;
